Add `bitdepth`, `samplingrate` and `codec` optional fields
opensubsonic/open-subsonic-api pull request #83
Opened 2024-01-13 16:08 UTC by GioF71

Hello, this is related to [this](https://github.com/opensubsonic/open-subsonic-api/discussions/64) discussion.
Thank you for your attention.

2024-01-13 16:24 UTC, Tolriq commented
We did not fully finished that discussion, we should also expose channelCount. Field doc should be more precise about the field values (with example in the doc to explain that it's full sample rate 44100 and no 44.1).
And we need to define a little more the codec field to avoid random values there. 

Like enforced lowercase, and decide if it's the full codec codes from ffmpeg or only the short usual ones. (full codec would be better)

2024-01-13 16:36 UTC, GioF71 commented
> We did not fully finished that discussion, we should also expose channelCount. Field doc should be more precise about the field values (with example in the doc to explain that it's full sample rate 44100 and no 44.1). And we need to define a little more the codec field to avoid random values there.
> 
> Like enforced lowercase, and decide if it's the full codec codes from ffmpeg or only the short usual ones. (full codec would be better)

Ops, sorry.
Some time passed so I though I had to do something myself in order to complete the change.
Do we need to close this PR, or can we keep it open so that I can push more changes?

Thank you

2024-01-13 16:38 UTC, Tolriq commented
The discussion can continue here it often works like that to finalize the details, without a PR people stops talking :p

2024-01-13 16:40 UTC, epoupon commented
Indeed we can add channelCount in this PR, but I would discuss codec/format related info in another PR as it is not straightforward

2024-01-13 16:49 UTC, dweymouth commented
I think we should publish a list of well-known codec values, and try to be fairly extensive, whether we do the short-form or the long-form codec strings. (And I'd probably suggest the short-form, because that's what already is used de-facto for the "format" arg to the stream endpoint)

2024-01-13 16:57 UTC, GioF71 commented
@dweymouth @epoupon @Tolriq will we update the discussion, or can we collect the 'missing' information here in this PR?

2024-01-13 16:59 UTC, GioF71 commented
> Indeed we can add channelCount in this PR, but I would discuss codec/format related info in another PR as it is not straightforward

If this is agreed, I can remove the "codec" entries from this PR and leave this aspect for another one.

2024-01-13 17:00 UTC, dweymouth commented
Let's return to the discussion for codec, but it's up to you @GioF71 if you want to do this PR without codec, or let it sit until we come to an agreement on how we want to handle codec

2024-01-13 17:03 UTC, Tolriq commented
I would say that all the data is related and that for a server to store and expose most of the data the codec will be extracted at the same time, it's better if how it should be exposed is defined at the same time to avoid some chosing something that won't work with a future decision.

2024-01-13 17:07 UTC, GioF71 commented
ok I'll leave the "codec" fields, and will update the rest according to the discussion.
Thank you

2024-01-13 17:20 UTC, epoupon commented
> I would say that all the data is related and that for a server to store and expose most of the data the codec will be extracted at the same time, it's better if how it should be exposed is defined at the same time to avoid some chosing something that won't work with a future decision.

Taglib can extract channel count, bitdepth and sampling rate out of the box, but this is more tricky to get exact info on formats and codecs used.
I would really "secure" first these three fields and spend some days/week debating on codec/formats (in the proposal of @dweymouth , there is a "FLAC audio in an OGG container (uncommon)" entry that is mixing codec and format, just to say that it will likely take some time to be agreed on...)

2024-01-13 17:29 UTC, Tolriq commented
Codec and transcoding format are unrelated as not clear enough, the format param is more container than codec. The codecs will be used in the future transcoding API as the formats/ container

2024-01-13 17:32 UTC, dweymouth commented
> The codecs will be used in the future transcoding API as the formats/ container

Not quite sure what you mean by this? Are you saying the client will execute something like `/stream?format=flac&container=flac,ogg` to request either OGG flac or standard flac?

2024-01-13 17:35 UTC, Tolriq commented
To be defined, but the idea is the client says I support that that that and that with contraints on things. Then server returns either the file can be direct played or should be transcoded with x and t param.

2024-01-13 18:28 UTC, sentriz commented
is this consistent with the transcodedContentType, transcodedSuffix fields that we have already?

2024-01-13 18:32 UTC, dweymouth commented
> is this consistent with the transcodedContentType, transcodedSuffix fields that we have already?

This would serve a different purpose as the contentType and extension fields are very non-specific about the actual codec/container. (eg there is no specific contentType for Apple Lossless, most servers would probably report `audio/mp4`). Suffix is also kind-of a useless field since file extensions don't matter at all (eg on Unix-like OSes you could have all your media files have no extension and it's fine because extension has nothing to do with the actual file type)

2024-04-02 09:48 UTC, Tolriq commented
Ok so since there's no movement on this one, let's remove the codec part and expose bitDepth, samplingRate and channelCount?

Would still be nice to continue the work on the codec/container/full codec ones.

2024-04-02 10:15 UTC, GioF71 commented
I agree.
I suppose we give some for the others to confirm and/or elaborate?

2024-04-02 11:24 UTC, epoupon commented
Fine for me!

2024-04-07 15:50 UTC, GioF71 commented
Ok, I have removed the last commit, which added the codec field, so we are back with only samplingRate and bitDepth.
Let me know if other changes are needed.

2024-04-07 15:59 UTC, Tolriq commented
Can you add the requested `channelCount` ? There's no debate about this is and it's needed also to know if a media is playable or not.

2024-04-07 16:01 UTC, GioF71 commented
> Can you add the requested `channelCount` ? There's no debate about this is and it's needed also to know if a media is playable or not.

Sorry, I missed that. I will update asap.

2024-04-07 16:40 UTC, Tolriq submitted a review, later dismissed

2024-04-07 18:29 UTC, epoupon approved these changes

2024-04-07 19:04 UTC, deluan requested changes

2024-04-07 19:04 UTC, deluan commented on content/en/docs/Responses/Child.md
> +| `channelCount` | `int` | No |     | The number of channels of the media. |
OpenSubsonic column should be "Yes"

2024-04-07 21:41 UTC, GioF71 commented on content/en/docs/Responses/Child.md
> +| `channelCount` | `int` | No |     | The number of channels of the media. |
Right, done that.

2024-04-08 01:24 UTC, deluan approved these changes

2024-04-08 04:48 UTC, epoupon approved these changes

2024-04-08 05:50 UTC, Tolriq approved these changes

2024-04-09 12:33 UTC, Tolriq commented
Small @dweymouth ping before merging just in case.

2024-04-09 22:02 UTC, dweymouth approved these changes

2024-04-10 06:01 UTC, merged